//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttendanceTable()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int AttendanceID { get; set; }
        public int StudentID { get; set; }
        public string Attendance { get; set; }
        public string AttendanceDate { get; set; }
        public Nullable<int> TeacherID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual TeacherTable TeacherTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
